/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Session cookie set */
                204: {
                    headers: {
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Problem"];
                429: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the current user's password
         * @description Revokes every other session. While `must_change_password` is set this is the
         *     only endpoint the session may reach; everything else answers 403.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        current_password: string;
                        new_password: string;
                    };
                };
            };
            responses: {
                /** @description Changed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's live sessions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"][];
                    };
                };
                401: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session's id as returned by GET /auth/sessions. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one session */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The session's id as returned by GET /auth/sessions. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The currency table, with each currency's exponent
         * @description Clients render money from `amount_minor` and `exponent`; this is where the
         *     exponents come from. HUF is 0-decimal.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Currency"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories */
        get: {
            parameters: {
                query?: {
                    kind?: "expense" | "income";
                    include_archived?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a category */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Archive a category
         * @description Archives rather than deletes. Historical transactions keep their category.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archived */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a category */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/categories/{id}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge one category into another
         * @description Rewrites every transaction and budget reference, archives the source, and
         *     leaves an alias behind so the old source name still resolves on import.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        into_id: number;
                    };
                };
            };
            responses: {
                /** @description Merged */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List category aliases */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alias"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a category alias */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        category_id: number;
                        source_name: string;
                        /** @default monefy */
                        source?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alias"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"][];
                    };
                };
            };
        };
        put?: never;
        /** Create an account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/aliases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a category alias */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Archive an account
         * @description Archives rather than deletes; historical rows keep their account.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Archived */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update an account */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                404: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        trace?: never;
    };
    "/accounts/aliases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List account aliases */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alias"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an account alias
         * @description Monefy names accounts after currencies, so the same logical account appears
         *     under different names across exports.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        account_id: number;
                        source_name: string;
                        /** @default monefy */
                        source?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alias"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/aliases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an account alias */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    category_id?: number;
                    account_id?: number;
                    kind?: "expense" | "income" | "transfer_in" | "transfer_out";
                    /** @description Free-text search over description and merchant */
                    q?: string;
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionPage"];
                    };
                };
            };
        };
        put?: never;
        /** Create a transaction */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get a transaction */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        /** Soft-delete a transaction */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a transaction */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransactionInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a transfer
         * @description Creates a paired transfer_out and transfer_in sharing one transfer_group_id.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        from_account_id: number;
                        to_account_id: number;
                        /** Format: date */
                        occurred_on: string;
                        amount: components["schemas"]["Money"];
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Budgets for a period */
        get: {
            parameters: {
                query: {
                    period: components["parameters"]["PeriodQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Budget"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed budgets across a period range
         * @description Applies one planned figure per category to every month in the range.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        from_period: string;
                        to_period: string;
                        items: {
                            category_id: number;
                            planned: components["schemas"]["Money"];
                        }[];
                    };
                };
            };
            responses: {
                /** @description Applied */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            periods_written?: number;
                            rows_written?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{category_id}/{period}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
                period: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Set one category's plan for one month */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    category_id: number;
                    period: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        planned: components["schemas"]["Money"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Budget"];
                    };
                };
                404: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        post?: never;
        /**
         * Remove a plan
         * @description An absent plan is "not planned", which is a different fact from a plan of
         *     zero, so this is not the same as setting it to 0.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    category_id: number;
                    period: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshots for a period
         * @description Returns every account with the previous month pre-filled, for the entry screen.
         */
        get: {
            parameters: {
                query: {
                    period: components["parameters"]["PeriodQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Snapshot"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Record a whole month at once
         * @description The confirm-or-adjust screen, written in one transaction so a half-saved
         *     month cannot exist. This is the endpoint behind the roughly thirty
         *     workbook cells the capital block used to need every month.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        period: string;
                        items: {
                            account_id: number;
                            amount?: components["schemas"]["Money"];
                            quantity_nano?: number | null;
                            note?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Written */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            period?: string;
                            rows_written?: number;
                        };
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{account_id}/{period}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
                period: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Record one account's balance
         * @description Writing to a computed parent is refused with 422: its value is the sum of
         *     its children. Exactly one of `amount` and `quantity_nano` must be given.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_id: number;
                    period: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        amount?: components["schemas"]["Money"];
                        quantity_nano?: number | null;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Snapshot"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        post?: never;
        /**
         * Remove one snapshot
         * @description A month with no snapshot is a gap. It is never interpolated.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    account_id: number;
                    period: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{period}/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                period: string;
            };
            cookie?: never;
        };
        /**
         * Snapshot versus transaction-implied balance
         * @description The snapshot is authoritative. The difference is reported so it can be
         *     investigated, and nothing is ever corrected automatically
         *     (docs/adr/0003-snapshot-reconcile-balances.md).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    period: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            period?: string;
                            note?: string;
                            items?: {
                                account_id?: number;
                                name?: string;
                                snapshot?: components["schemas"]["Money"] | null;
                                implied?: components["schemas"]["Money"] | null;
                                /** @description snapshot minus implied; null when either side is absent. */
                                difference?: components["schemas"]["Money"] | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/net-worth-in/{currency}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                currency: string;
            };
            cookie?: never;
        };
        /**
         * Net worth expressed in another currency
         * @description The workbook's rows 71-72, at each period's own rate rather than today's.
         */
        get: {
            parameters: {
                query: {
                    period: components["parameters"]["PeriodQuery"];
                };
                header?: never;
                path: {
                    currency: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            period?: string;
                            currency?: string;
                            base_currency?: string;
                            general?: components["schemas"]["Money"] | null;
                            value?: components["schemas"]["Money"] | null;
                        };
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import batch history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportBatch"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Upload a file for import
         * @description Stores the raw file, parses it, resolves aliases and dedups. Nothing is
         *     written to the ledger until POST /imports/{id}/commit.
         *
         *     Re-uploading a file whose sha256 was already committed returns 200 with
         *     that original batch and `already_imported: true`, rather than
         *     reprocessing it. A fresh export containing the same rows is a different
         *     file and is analysed normally, reporting them as duplicates.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description This exact file was already imported; the original batch is returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportBatch"];
                    };
                };
                /** @description Batch created; previewed or awaiting mapping */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportBatch"];
                    };
                };
                413: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Preview a batch
         * @description Re-runs the analysis against the retained file, so the counts, the
         *     suggestions and the vanished list always reflect the database as it is
         *     now rather than as it was at upload.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportPreview"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{id}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** List the lines of a batch */
        get: {
            parameters: {
                query?: {
                    status?: "new" | "duplicate" | "unmapped" | "rejected" | "committed";
                    limit?: number;
                };
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportRow"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{id}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve unmapped names
         * @description Records each decision as an alias, then re-runs the analysis. A name
         *     mapped here never asks again. Mapping onto a category that does not yet
         *     exist is two steps: POST /categories, then map onto the new id.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        categories?: components["schemas"]["ImportMapping"][];
                        accounts?: components["schemas"]["ImportMapping"][];
                    };
                };
            };
            responses: {
                /** @description Batch re-resolved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportPreview"];
                    };
                };
                409: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit a previewed batch
         * @description Rejected with 409 when rows_unmapped is greater than zero.
         *     This is the guarantee against silently discarding unrecognised categories.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Committed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportBatch"];
                    };
                };
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revert a committed batch */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reverted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportBatch"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan versus actual for a period */
        get: {
            parameters: {
                query: {
                    period: components["parameters"]["PeriodQuery"];
                    /**
                     * @description contemporaneous values each period at its own rate.
                     *     constant values everything at today's rate, reproducing the legacy spreadsheet.
                     */
                    valuation?: components["parameters"]["Valuation"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BudgetReport"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Roll-up rows across a range of periods
         * @description The workbook's rows 27, 31, 32 and 33 for every month in the range.
         *     Defaults to the fiscal year containing the most recent data.
         *
         *     A month with no data reports `recorded: false` and null for every money
         *     field. It is never 0 and never the sheet's -1 sentinel.
         */
        get: {
            parameters: {
                query?: {
                    /** @description First month, inclusive. Defaults with `to` to the latest fiscal year. */
                    from?: components["parameters"]["FromPeriod"];
                    /** @description Last month, inclusive. */
                    to?: components["parameters"]["ToPeriod"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportSummary"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The year grid — categories by month
         * @description The workbook's rows 9-26 with columns C (average), E-P (the months) and T
         *     (results), plus the roll-up rows underneath.
         */
        get: {
            parameters: {
                query?: {
                    /** @description First month, inclusive. Defaults with `to` to the latest fiscal year. */
                    from?: components["parameters"]["FromPeriod"];
                    /** @description Last month, inclusive. */
                    to?: components["parameters"]["ToPeriod"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReportCategories"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/capital": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Net worth, allocation and runway */
        get: {
            parameters: {
                query: {
                    period: components["parameters"]["PeriodQuery"];
                    /**
                     * @description contemporaneous values each period at its own rate.
                     *     constant values everything at today's rate, reproducing the legacy spreadsheet.
                     */
                    valuation?: components["parameters"]["Valuation"];
                    burn_mode?: "essential_planned" | "actual_trailing_3" | "actual_trailing_12" | "legacy_blend";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CapitalReport"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/capital/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Net worth over time, with the real and FX split */
        get: {
            parameters: {
                query?: {
                    /** @description First month, inclusive. Defaults with `to` to the latest fiscal year. */
                    from?: components["parameters"]["FromPeriod"];
                    /** @description Last month, inclusive. */
                    to?: components["parameters"]["ToPeriod"];
                    burn_mode?: "essential_planned" | "actual_trailing_3" | "actual_trailing_12" | "legacy_blend";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            from?: string;
                            to?: string;
                            base_currency?: string;
                            burn_mode?: string;
                            points?: {
                                period?: string;
                                recorded?: boolean;
                                general?: components["schemas"]["Money"] | null;
                                ready_for_usage?: components["schemas"]["Money"] | null;
                                runway_months?: number | null;
                                change?: components["schemas"]["CapitalChange"];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All settings with provider state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Setting"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The configured rate sources */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Provider"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a setting */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        mode?: "manual" | "auto";
                        /**
                         * @description The user's own figure. It wins over the provider's whenever it
                         *     is present, in either mode.
                         */
                        manual_value?: string;
                        /**
                         * @description Drops the override and goes back to the provider's value.
                         *     Omitting `manual_value` and sending `clear_manual: true` are
                         *     different requests: the first leaves the override alone.
                         */
                        clear_manual?: boolean;
                        provider_key?: string;
                        refresh_seconds?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Setting"];
                    };
                };
                404: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        trace?: never;
    };
    "/settings/{key}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force a provider fetch now
         * @description A provider outage is **not** an error here. The request succeeds, the
         *     message lands in `last_error`, the previous `last_value` stands and the
         *     setting reads as stale. Nothing a user is looking at breaks because a free
         *     API is down (docs/adr/0009-dated-fx-provider-chain.md).
         *
         *     Refreshing a manual setting is refused with 422: there is no provider to
         *     fetch from.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Refreshed, or last value retained on failure */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Setting"];
                    };
                };
                404: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fx/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rate history */
        get: {
            parameters: {
                query?: {
                    base?: string;
                    quote?: string;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FxRate"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fx/rates/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The most recent rate per currency, with its age
         * @description FX markets close, so weekend and holiday gaps are normal rather than errors.
         *     `age_days` is what the UI badges as staleness.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            rate?: components["schemas"]["FxRate"];
                            age_days?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Built-in and user-defined metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Metric"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse a metric definition without saving */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        definition: string;
                    };
                };
            };
            responses: {
                /** @description Parse result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            valid?: boolean;
                            errors?: string[];
                            references?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/link-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint a single-use link code
         * @description A six-character code, valid once, for ten minutes. Send `/link <code>` from
         *     the chat you want to import from. The code is shown once and cannot be read
         *     back — it is a credential for as long as it lives.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: string;
                            /** Format: date-time */
                            expires_at?: string;
                            instructions?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The chats linked to this account */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TelegramLink"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/links/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a link
         * @description The chat can import nothing from the moment this returns.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export everything this user owns */
        get: {
            parameters: {
                query?: {
                    format?: "json" | "csv";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Unhealthy while the schema version is behind the binary's expectation.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                503: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        Money: {
            /**
             * Format: int64
             * @description Value in minor units. HUF has exponent 0, so 1000 means 1000 HUF.
             */
            amount_minor: number;
            currency: string;
            exponent: number;
        };
        BaseMoney: components["schemas"]["Money"] & {
            fx_rate_id?: number | null;
            /** Format: date */
            as_of_date?: string | null;
        };
        User: {
            id?: number;
            /** Format: email */
            email?: string;
            display_name?: string | null;
            /** @enum {string} */
            role?: "admin" | "user" | "readonly";
            base_currency?: string;
            timezone?: string;
            fiscal_year_start_month?: number;
            /** @description While true, every endpoint except POST /auth/password answers 403. */
            must_change_password?: boolean;
        };
        Session: {
            /**
             * @description The session's identifier. It is the SHA-256 of the token, not the token
             *     itself, so listing sessions never exposes a usable credential.
             */
            id?: string;
            user_agent?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            expires_at?: string;
            /** @description True for the session making the request. */
            current?: boolean;
        };
        Currency: {
            code?: string;
            /** @description Decimal places. HUF is 0. */
            exponent?: number;
            symbol?: string;
            name?: string;
        };
        Category: {
            id?: number;
            name?: string;
            /** @enum {string} */
            kind?: "expense" | "income";
            /** @description Membership of Possible Minimum */
            is_essential?: boolean;
            icon?: string | null;
            color?: string | null;
            sort_order?: number;
            parent_id?: number | null;
            /** Format: date-time */
            archived_at?: string | null;
        };
        CategoryInput: {
            name: string;
            /** @enum {string} */
            kind: "expense" | "income";
            /** @default false */
            is_essential: boolean;
            icon?: string;
            color?: string;
            sort_order?: number;
            parent_id?: number | null;
        };
        Alias: {
            id?: number;
            source?: string;
            source_name?: string;
            target_id?: number;
            target_name?: string;
        };
        Account: {
            id?: number;
            name?: string;
            /** @enum {string} */
            asset_class?: "cash" | "bank" | "deposit" | "investment" | "metal" | "crypto" | "other";
            currency?: string;
            is_liquid?: boolean;
            counts_toward_net_worth?: boolean;
            price_ticker?: string | null;
            cost_basis?: components["schemas"]["Money"];
            parent_id?: number | null;
            sort_order?: number;
            /** Format: date-time */
            archived_at?: string | null;
            /** @description Parent accounts are summed from children and reject direct values. */
            is_computed?: boolean;
        };
        AccountInput: {
            name: string;
            /** @enum {string} */
            asset_class: "cash" | "bank" | "deposit" | "investment" | "metal" | "crypto" | "other";
            currency: string;
            /** @default true */
            is_liquid: boolean;
            /** @default true */
            counts_toward_net_worth: boolean;
            price_ticker?: string;
            /** Format: int64 */
            cost_basis_minor?: number | null;
            parent_id?: number | null;
            sort_order?: number;
        };
        Transaction: {
            id?: number;
            account_id?: number;
            account_name?: string;
            category_id?: number | null;
            category_name?: string;
            /** Format: date */
            occurred_on?: string;
            /** @enum {string} */
            kind?: "expense" | "income" | "transfer_in" | "transfer_out";
            amount?: components["schemas"]["Money"];
            base_amount?: components["schemas"]["BaseMoney"];
            description?: string | null;
            merchant?: string | null;
            occurrence?: number;
            /**
             * @description True when base_amount is null because no rate covered this date. The
             *     write is never blocked by a missing rate, so the client is told instead.
             */
            unconverted?: boolean;
            transfer_group_id?: number | null;
            import_batch_id?: number | null;
        };
        TransactionInput: {
            account_id: number;
            /** @description Required for expense and income; forbidden for transfers. */
            category_id?: number | null;
            /** Format: date */
            occurred_on: string;
            /** @enum {string} */
            kind: "expense" | "income";
            amount: components["schemas"]["Money"];
            description?: string;
            merchant?: string;
        };
        TransactionPage: {
            items?: components["schemas"]["Transaction"][];
            next_cursor?: string | null;
            has_more?: boolean;
        };
        Budget: {
            category_id?: number;
            category_name?: string;
            period?: string;
            planned?: components["schemas"]["Money"];
        };
        Snapshot: {
            account_id?: number;
            account_name?: string;
            period?: string;
            amount?: components["schemas"]["Money"] | null;
            /** @description Alternative to amount, for metals and crypto priced by a provider. */
            quantity_nano?: number | null;
            base_amount?: components["schemas"]["Money"] | null;
            /** @description Prior month, for pre-filling the entry screen. */
            previous_amount?: components["schemas"]["Money"] | null;
            asset_class?: string;
            currency?: string;
            is_liquid?: boolean;
            counts_toward_net_worth?: boolean;
            /**
             * @description A parent account. Its value is the sum of its children and a direct
             *     write is refused with 422.
             */
            computed?: boolean;
            /** @description Base-currency value, rolled up for a parent. */
            value?: components["schemas"]["Money"] | null;
            note?: string | null;
        };
        ImportBatch: {
            id?: number;
            source?: string;
            /** @enum {string} */
            origin?: "web" | "telegram" | "cli";
            filename?: string | null;
            /** @enum {string} */
            status?: "received" | "parsed" | "needs_mapping" | "previewed" | "committed" | "reverted" | "failed";
            rows_total?: number;
            rows_new?: number;
            rows_duplicate?: number;
            rows_unmapped?: number;
            rows_rejected?: number;
            file_sha256?: string;
            error?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            committed_at?: string | null;
            /** Format: date-time */
            reverted_at?: string | null;
            /** @description This exact file had already been committed; nothing was reprocessed. */
            already_imported?: boolean;
        };
        ImportMapping: {
            /** @description The name exactly as it appears in the file, untrimmed. */
            source_name: string;
            target_id: number;
        };
        ImportRow: {
            id?: number;
            line_no?: number;
            raw_line?: string;
            /** Format: date */
            occurred_on?: string | null;
            account_name?: string;
            category_name?: string;
            amount?: components["schemas"]["Money"];
            description?: string | null;
            /** @enum {string} */
            status?: "new" | "duplicate" | "unmapped" | "rejected" | "committed";
            reason?: string;
            transaction_id?: number | null;
        };
        /**
         * @description One source name blocking the batch. row_count makes the cost of the
         *     decision visible, which is the point of the mapping screen.
         */
        ImportUnmappedName: {
            source_name?: string;
            row_count?: number;
            reason?: string;
            /** @description A proposal, never an application. Confirming it is what creates the alias. */
            suggestion?: {
                id?: number;
                name?: string;
                /**
                 * @description high for a case or whitespace variant, medium for an edit-distance match.
                 * @enum {string}
                 */
                confidence?: "high" | "medium";
            } | null;
        };
        ImportVanishedRow: {
            transaction_id?: number;
            /** Format: date */
            occurred_on?: string;
            account_name?: string;
            category_name?: string;
            amount?: components["schemas"]["Money"];
            description?: string;
        };
        ImportPreview: {
            batch_id?: number;
            filename?: string;
            /** @enum {string} */
            origin?: "web" | "telegram" | "cli";
            /** @enum {string} */
            status?: "received" | "parsed" | "needs_mapping" | "previewed" | "committed" | "reverted" | "failed";
            date_range?: {
                /** Format: date */
                from?: string;
                /** Format: date */
                to?: string;
            } | null;
            rows_total?: number;
            rows_new?: number;
            rows_duplicate?: number;
            rows_unmapped?: number;
            rows_rejected?: number;
            /** @description Distinct calendar months containing at least one row. */
            months_touched?: number;
            unmapped_categories?: components["schemas"]["ImportUnmappedName"][];
            unmapped_accounts?: components["schemas"]["ImportUnmappedName"][];
            /** @description Stored rows absent from the file's date range. Flagged, never auto-deleted. */
            vanished?: components["schemas"]["ImportVanishedRow"][];
            rejected?: components["schemas"]["ImportRow"][];
            by_currency?: {
                [key: string]: number;
            };
            warnings?: string[];
            /** Format: date-time */
            committed_at?: string | null;
            /** Format: date-time */
            reverted_at?: string | null;
        };
        /**
         * @description One month of the roll-up rows. Every money field is null when
         *     `recorded` is false — absent is not zero.
         */
        PeriodSummary: {
            period?: string;
            recorded?: boolean;
            spend_total?: components["schemas"]["Money"] | null;
            planned_total?: components["schemas"]["Money"];
            possible_minimum?: components["schemas"]["Money"];
            income?: components["schemas"]["Money"] | null;
            diff?: components["schemas"]["Money"] | null;
            /** @description Unclamped. Null when income is zero. */
            saved_percent?: number | null;
            unconverted?: number;
        };
        ReportSummary: {
            from?: string;
            to?: string;
            base_currency?: string;
            fiscal_year?: string;
            periods?: components["schemas"]["PeriodSummary"][];
        };
        CategoryCell: {
            period?: string;
            /** @description Null for an unrecorded month. The grid renders that blank, never 0. */
            actual?: components["schemas"]["Money"] | null;
            planned?: components["schemas"]["Money"] | null;
            ratio?: number | null;
            /** @enum {string} */
            state?: "severely_over" | "over" | "approaching" | "within" | "zero" | "not_recorded";
            state_label?: string;
        };
        CategorySeries: {
            category_id?: number;
            name?: string;
            icon?: string | null;
            color?: string | null;
            is_essential?: boolean;
            archived?: boolean;
            /** @description Column C — mean over recorded months only. */
            average?: components["schemas"]["Money"] | null;
            /** @description Column T — sum over recorded months, without the sheet's -1 sentinel. */
            total?: components["schemas"]["Money"] | null;
            cells?: components["schemas"]["CategoryCell"][];
        };
        ReportCategories: {
            from?: string;
            to?: string;
            base_currency?: string;
            periods?: string[];
            recorded?: {
                [key: string]: boolean;
            };
            categories?: components["schemas"]["CategorySeries"][];
            summary?: components["schemas"]["PeriodSummary"][];
        };
        BudgetReport: {
            period?: string;
            valuation?: string;
            base_currency?: string;
            /**
             * @description Transactions in this period with no rate for their date. They are
             *     excluded from the totals and reported rather than counted as zero.
             */
            unconverted?: number;
            /** @description null when the period recorded nothing at all. */
            spend_total?: components["schemas"]["Money"] | null;
            planned_total?: components["schemas"]["Money"];
            income?: components["schemas"]["Money"] | null;
            diff?: components["schemas"]["Money"] | null;
            /** @description Ratio, unclamped. Negative when spend exceeds income; null when income is zero. */
            saved_percent?: number | null;
            possible_minimum?: components["schemas"]["Money"];
            categories?: {
                category_id?: number;
                name?: string;
                /** @description null means the period has no recorded data, distinct from zero. */
                actual?: components["schemas"]["Money"] | null;
                icon?: string | null;
                color?: string | null;
                is_essential?: boolean;
                /** @description null when no plan was recorded, which differs from a plan of zero. */
                planned?: components["schemas"]["Money"] | null;
                /**
                 * @description Mean over every recorded month, the workbook's column C. It holds
                 *     steady as the month on screen changes, and is null until there is
                 *     data to average — never 0.
                 */
                average?: components["schemas"]["Money"] | null;
                ratio?: number | null;
                /** @enum {string} */
                state?: "severely_over" | "over" | "approaching" | "within" | "zero" | "not_recorded";
                /**
                 * @description Accessible wording for the state, so colour is never the only
                 *     signal and every client says the same thing.
                 */
                state_label?: string;
            }[];
        };
        /**
         * @description The month's movement, split into what was actually saved and what the
         *     currencies did. The workbook reported only their sum, so a month when the
         *     hryvnia moved looked identical to a month of genuine saving (deviation D8).
         */
        CapitalChange: {
            /** @description false when there is no previous month to compare against. */
            recorded?: boolean;
            total?: components["schemas"]["Money"] | null;
            real?: components["schemas"]["Money"] | null;
            fx?: components["schemas"]["Money"] | null;
        };
        CapitalReport: {
            period?: string;
            base_currency?: string;
            /** @description Null for a month with no balances recorded at all. */
            general?: components["schemas"]["Money"] | null;
            ready_for_usage?: components["schemas"]["Money"] | null;
            /** @description Null when the burn rate is zero — "forever" is not a number of months. */
            runway_months?: number | null;
            burn_mode?: string;
            burn_rate?: components["schemas"]["Money"] | null;
            change?: components["schemas"]["CapitalChange"];
            /**
             * @description Leaf accounts only, converted to base currency first, so the shares sum
             *     to exactly 1. The sheet's doughnut plotted parents alongside their
             *     children and divided unconverted amounts, reaching about 162% with
             *     `Cash HUF` at 41.4% (deviation D6).
             */
            allocation?: {
                account_id?: number;
                name?: string;
                asset_class?: string;
                value?: components["schemas"]["Money"];
                share?: number;
            }[];
            accounts?: components["schemas"]["Snapshot"][];
        };
        TelegramLink: {
            id?: number;
            chat_id?: number | null;
            /** Format: date-time */
            expires_at?: string;
            /** Format: date-time */
            linked_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
            /** @description Bound to a chat and not revoked. At most one per chat. */
            live?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        /**
         * @description One configurable value plus how it is maintained. Values are decimal text,
         *     never floats, for the same reason fx_rate.rate is.
         */
        Setting: {
            key?: string;
            /** @enum {string} */
            mode?: "manual" | "auto";
            manual_value?: string | null;
            provider_key?: string | null;
            /** @description What the application uses — the manual value when there is one. */
            effective_value?: string | null;
            /**
             * @description The provider's latest figure. It is kept even while a manual value
             *     overrides it, so the screen can say "auto suggested 51.08 — you set
             *     51.00".
             */
            last_value?: string | null;
            /** @description A manual value is sitting on top of a provider value. */
            overridden?: boolean;
            refresh_seconds?: number;
            /** Format: date-time */
            last_fetched_at?: string | null;
            last_error?: string | null;
            /**
             * @description An auto setting that has missed its refresh window. A manual setting is
             *     never stale — nobody promised to update it.
             */
            stale?: boolean;
            /** Format: date-time */
            updated_at?: string;
        };
        /**
         * @description A configured rate source. All are free and keyless; `kind` has exactly
         *     three values and `broker` is not one of them.
         */
        Provider: {
            key?: string;
            /** @enum {string} */
            kind?: "fx" | "metal" | "crypto";
            endpoint?: string;
            priority?: number;
            enabled?: boolean;
        };
        FxRate: {
            /** Format: date */
            as_of_date?: string;
            base?: string;
            quote?: string;
            /** @description Decimal string, parsed into an exact rational. Never a float. */
            rate?: string;
            source?: string;
            /** Format: date-time */
            fetched_at?: string;
        };
        Metric: {
            key?: string;
            label?: string;
            definition?: string;
            is_builtin?: boolean;
        };
    };
    responses: {
        /** @description RFC 7807 problem document */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description First month, inclusive. Defaults with `to` to the latest fiscal year. */
        FromPeriod: string;
        /** @description Last month, inclusive. */
        ToPeriod: string;
        Id: number;
        PeriodQuery: string;
        /**
         * @description contemporaneous values each period at its own rate.
         *     constant values everything at today's rate, reproducing the legacy spreadsheet.
         */
        Valuation: "contemporaneous" | "constant";
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
